### ISSUE TITLE
KeyError: 196

### ISSUE THREAD

**Issue by vtruong68** [alexlance/signal-message-exporter#2]
I'm getting a key error after the following code: `docker run -e SIG_KEY -e SIG_FILE -it -v ${PWD}:/root/ workspace python3 signal-message-exporter.py`

Output:
```
Reading backup file...
Read entire backup file...

done!

Exporting backup into 'bits//'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Writing Attachments...
Writing Avatars...
Writing SharedPrefFrame(s)...
Writing KeyValueFrame(s)...
Writing StickerFrames...
Writing EndFrame...
Writing database...
Done!

Traceback (most recent call last):
  File "/root/signal-message-exporter.py", line 218, in <module>
    GROUPS = get_groups()
  File "/root/signal-message-exporter.py", line 68, in get_groups
    groups_by_id[g['recipient_id']].append(ADDRESSES[int(member_recipient_id)])
KeyError: 196
```

**Comment by alexlance** [comment]
Hi there, I've added an exception handler in the code - run `git pull` to obtain the latest code and try again.

**Comment by vtruong68** [comment]
Worked like a charm. Lost a few messages as expected, but I can live with that as opposed to losing everything to Signal.

```
2022-10-18 00:12:57 - INFO - Finished media export. Messages exported: 2337 Errors: 6
2022-10-18 00:13:03 - INFO - Complete.
2022-10-18 00:13:03 - INFO - Created: sms-backup-restore.xml
2022-10-18 00:13:03 - INFO - Now install SMS Backup & Restore and choose this file to restore
2022-10-18 00:13:03 - ERROR - WARNING: 9 messages were skipped! I.e. Not all messages were exported successfully. See output above for the messages that were skipped
```

**Comment by alexlance** [comment]
Ah nice one! So happy to hear it! Closing issue.
